// This file is generated by packages/schema/scripts/generate-types.mjs.
// Do not edit it by hand.

/**
 * Reference schema for shared event fields. Not intended as a $ref target — each event schema must be self-contained.
 */
export interface BaseEvent {
  /**
   * Discriminant for the event union.
   */
  kind: string;
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team responsible for the event.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical card event normalized into Campos pitch space.
 */
export interface CardEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "card";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team receiving the card.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * The type of card shown.
   */
  cardType: "yellow" | "red" | "second-yellow";
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical carry event normalized into Campos pitch space.
 */
export interface CarryEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "carry";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team making the carry.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * Campos pitch x-coordinate of the carry end position. Null when end coordinates are unavailable.
   */
  endX: number | null;
  /**
   * Campos pitch y-coordinate of the carry end position. Null when end coordinates are unavailable.
   */
  endY: number | null;
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical clearance event normalized into Campos pitch space.
 */
export interface ClearanceEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "clearance";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team making the clearance.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Competition metadata. Only id is required.
 */
export interface Competition {
  id: string;
  name?: string | null;
  country?: string | null;
  [k: string]: unknown;
}

/**
 * Canonical duel event normalized into Campos pitch space.
 */
export interface DuelEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "duel";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team engaging in the duel.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * Whether the duel was contested in the air or on the ground.
   */
  duelType: "aerial" | "ground";
  /**
   * Whether the duel was won or lost.
   */
  duelOutcome: "won" | "lost";
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical foul committed event normalized into Campos pitch space.
 */
export interface FoulCommittedEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "foul-committed";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team committing the foul.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Game metadata. Only id is required.
 */
export interface Game {
  id: string;
  date?: string | null;
  homeTeamId?: string | null;
  awayTeamId?: string | null;
  homeScore?: number | null;
  awayScore?: number | null;
  seasonId?: string | null;
  competitionId?: string | null;
  [k: string]: unknown;
}

/**
 * Canonical goalkeeper action event normalized into Campos pitch space.
 */
export interface GoalkeeperEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "goalkeeper";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team whose goalkeeper performed the action.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * The type of goalkeeper action performed.
   */
  actionType: "save" | "claim" | "punch" | "keeper-pick-up";
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical interception event normalized into Campos pitch space.
 */
export interface InterceptionEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "interception";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team making the interception.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Context required by some adapters to normalize events into Campos pitch space.
 */
export interface MatchContext {
  matchId: string;
  homeTeamId: string;
  awayTeamId: string;
  /**
   * For non-attack-relative feeds (e.g. Opta F24), `homeAttacksToward` tells the adapter which way the home team attacked in each period so it can rotate coordinates into the canonical attacker frame. For attack-relative feeds the period directions are not consulted by the adapter.
   */
  periods?: {
    firstHalf: {
      homeAttacksToward: "increasing-x" | "decreasing-x";
    };
    secondHalf: {
      homeAttacksToward: "increasing-x" | "decreasing-x";
    };
    extraTimeFirstHalf?: {
      homeAttacksToward: "increasing-x" | "decreasing-x";
    };
    extraTimeSecondHalf?: {
      homeAttacksToward: "increasing-x" | "decreasing-x";
    };
  } | null;
  /**
   * Set true for feeds where coordinates are already attack-relative (x=100 always toward the goal being attacked, for all teams in all periods). Opta expected-goals feeds use this encoding; standard Opta F24 match-event feeds do not.
   */
  attackRelative?: boolean;
  pitchDimensions?: {
    length: number;
    width: number;
  } | null;
}

/**
 * Canonical home and away team sheets for a match.
 */
export interface MatchLineups {
  /**
   * Stable match identifier when known.
   */
  matchId?: string | null;
  /**
   * Home team sheet when decoded.
   */
  home?: TeamSheet | null;
  /**
   * Away team sheet when decoded.
   */
  away?: TeamSheet | null;
}

/**
 * Canonical scoreline-side summary for one team in a match header or live/result card.
 */
export interface MatchSummaryTeam {
  /**
   * Stable team identifier when the source provides one.
   */
  teamId?: string | null;
  /**
   * Display-ready team label.
   */
  teamLabel: string;
  /**
   * Current or final goals for this team.
   */
  score?: number | null;
  /**
   * Team expected-goals total when the source provides it.
   */
  xg?: number | null;
  /**
   * Penalty shootout or tiebreak goals when the source exposes them.
   */
  penalties?: number | null;
  /**
   * Team red-card count when the source exposes it.
   */
  redCards?: number | null;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical live/result/header summary for a single football match.
 */
export interface MatchSummary {
  /**
   * Stable match identifier in the source dataset when known.
   */
  matchId: string;
  /**
   * Display-ready competition label when known.
   */
  competitionLabel?: string | null;
  /**
   * Display-ready season label when known.
   */
  seasonLabel?: string | null;
  /**
   * Kickoff time as an ISO-8601 timestamp when known.
   */
  kickoff?: string | null;
  /**
   * Canonical match status for header and live/result UI.
   */
  status:
    | "scheduled"
    | "live"
    | "halftime"
    | "finished"
    | "postponed"
    | "canceled"
    | "abandoned"
    | "suspended"
    | "awarded"
    | "unknown";
  /**
   * Provider or display-ready status label when useful (for example FT, AET, AP, 1st half, or Postponed).
   */
  statusLabel?: string | null;
  /**
   * How a finished match was resolved when the source exposes it. Null when unknown or not applicable.
   */
  resolvedIn?: "regulation" | "extra-time" | "shootout" | "forfeit" | null;
  /**
   * Winner of a penalty shootout when resolvedIn is 'shootout'. Null otherwise.
   */
  shootoutWinner?: "home" | "away" | null;
  /**
   * Current live match minute when the source exposes it cleanly. Currently no adapter populates this; reserved for future live feeds.
   */
  minute?: number | null;
  /**
   * Venue label when known.
   */
  venue?: string | null;
  /**
   * Attendance when the source exposes it.
   */
  attendance?: number | null;
  home: MatchSummaryTeam;
  away: MatchSummaryTeam;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical pass event normalized into Campos pitch space.
 */
export interface PassEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "pass";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team making the pass.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * Campos pitch x-coordinate of the pass destination. Null when end coordinates are unavailable.
   */
  endX: number | null;
  /**
   * Campos pitch y-coordinate of the pass destination. Null when end coordinates are unavailable.
   */
  endY: number | null;
  /**
   * Euclidean distance of the pass in Campos coordinate units. Null when end coordinates are unavailable.
   */
  length: number | null;
  /**
   * Pass angle in radians from the positive x-axis. Null when end coordinates are unavailable.
   */
  angle: number | null;
  /**
   * Display-ready name of the pass recipient when available.
   */
  recipient: string | null;
  passType:
    | "ground"
    | "low"
    | "high"
    | "through-ball"
    | "cross"
    | "corner"
    | "free-kick"
    | "goal-kick"
    | "throw-in"
    | "kick-off"
    | "other"
    | null;
  /**
   * Pass outcome. Null when the provider does not supply pass results.
   */
  passResult: "complete" | "incomplete" | "offside" | "out" | null;
  isAssist: boolean;
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Player metadata. Only id is required.
 */
export interface Player {
  id: string;
  name?: string | null;
  teamId?: string | null;
  jerseyNumber?: number | null;
  position?: string | null;
  [k: string]: unknown;
}

/**
 * Canonical defensive-pressure event normalized into Campos pitch space. `counterpress` marks pressure applied within 5 seconds of losing possession, per StatsBomb's definition.
 */
export interface PressureEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "pressure";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team applying pressure.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * True when the pressure was applied within 5 seconds of losing possession (StatsBomb's counterpress definition). False for regular open-play pressures. Null when the source provider does not classify counterpress (for example Opta). Note: pressure coordinates are in the PRESSING team's attacker-perspective frame, so `teamId` always identifies the pressing team — consumers rendering from the in-possession team's perspective must flip axes.
   */
  counterpress: boolean | null;
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical ball recovery event normalized into Campos pitch space.
 */
export interface RecoveryEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "recovery";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team recovering the ball.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Season metadata. Only id is required.
 */
export interface Season {
  id: string;
  name?: string | null;
  competitionId?: string | null;
  [k: string]: unknown;
}

/**
 * Canonical shot event normalized into Campos pitch space.
 */
export interface ShotEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "shot";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team taking the shot.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * Campos pitch x-coordinate where the shot ended (e.g. freeze-frame or carry-through location toward goal or wide). Null when unavailable. Must be present with endY when set.
   */
  endX?: number | null;
  /**
   * Campos pitch y-coordinate where the shot ended. Null when unavailable. Must be present with endX when set.
   */
  endY?: number | null;
  /**
   * Expected goals value from the provider model.
   */
  xg: number | null;
  /**
   * Post-shot expected goals (xG on target). Null when unavailable.
   */
  xgot?: number | null;
  outcome: "goal" | "saved" | "blocked" | "off-target" | "hit-woodwork" | "other";
  bodyPart: "left-foot" | "right-foot" | "head" | "other" | null;
  isOwnGoal: boolean;
  isPenalty: boolean;
  context:
    | "regular-play"
    | "fast-break"
    | "set-piece"
    | "from-corner"
    | "direct-free-kick"
    | "penalty"
    | "other"
    | null;
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Where the shot crossed the goal plane on the horizontal axis (0 = left post, 100 = right post). Null when not available or shot missed wide.
   */
  goalMouthY?: number | null;
  /**
   * Where the shot crossed the goal plane on the vertical axis (0 = ground, 100 = crossbar height). Null when not available or shot missed high/wide.
   */
  goalMouthZ?: number | null;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical shot event normalized into Campos pitch space.
 */
export interface Shot {
  /**
   * Discriminant for the event union.
   */
  kind: "shot";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team taking the shot.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * Campos pitch x-coordinate where the shot ended (e.g. freeze-frame or carry-through location toward goal or wide). Null when unavailable. Must be present with endY when set.
   */
  endX?: number | null;
  /**
   * Campos pitch y-coordinate where the shot ended. Null when unavailable. Must be present with endX when set.
   */
  endY?: number | null;
  /**
   * Expected goals value from the provider model.
   */
  xg: number | null;
  /**
   * Post-shot expected goals (xG on target). Null when unavailable.
   */
  xgot?: number | null;
  outcome: "goal" | "saved" | "blocked" | "off-target" | "hit-woodwork" | "other";
  bodyPart: "left-foot" | "right-foot" | "head" | "other" | null;
  isOwnGoal: boolean;
  isPenalty: boolean;
  context:
    | "regular-play"
    | "fast-break"
    | "set-piece"
    | "from-corner"
    | "direct-free-kick"
    | "penalty"
    | "other"
    | null;
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Where the shot crossed the goal plane on the horizontal axis (0 = left post, 100 = right post). Null when not available or shot missed wide.
   */
  goalMouthY?: number | null;
  /**
   * Where the shot crossed the goal plane on the vertical axis (0 = ground, 100 = crossbar height). Null when not available or shot missed high/wide.
   */
  goalMouthZ?: number | null;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical substitution event normalized into Campos pitch space.
 */
export interface SubstitutionEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "substitution";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team making the substitution.
   */
  teamId: string;
  /**
   * Provider player identifier for the player coming off when available.
   */
  playerId: string | null;
  /**
   * Display-ready name of the player coming off when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * Provider player identifier for the player coming on when available.
   */
  playerInId: string | null;
  /**
   * Display-ready name of the player coming on when present in the source feed.
   */
  playerInName: string | null;
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical tackle event normalized into Campos pitch space.
 */
export interface TackleEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "tackle";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team making the tackle.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * Whether the tackle was successful.
   */
  tackleOutcome: "won" | "lost";
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical take-on (dribble attempt) event normalized into Campos pitch space.
 */
export interface TakeOnEvent {
  /**
   * Discriminant for the event union.
   */
  kind: "take-on";
  /**
   * Stable Campos event identifier.
   */
  id: string;
  /**
   * Match identifier in the consuming app or source dataset.
   */
  matchId: string;
  /**
   * Identifier for the team attempting the take-on.
   */
  teamId: string;
  /**
   * Provider player identifier when available.
   */
  playerId: string | null;
  /**
   * Display-ready player name when present in the source feed.
   */
  playerName: string | null;
  minute: number;
  /**
   * Stoppage-time minute offset, null when not in added time.
   */
  addedMinute: number | null;
  second: number;
  /**
   * Match period: 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
   */
  period: 1 | 2 | 3 | 4 | 5;
  /**
   * Campos pitch x-coordinate (0 = own goal line, 100 = opposition goal line). Null for events without coordinates.
   */
  x: number | null;
  /**
   * Campos pitch y-coordinate (0 = attacker's right, 100 = attacker's left). Null for events without coordinates.
   */
  y: number | null;
  /**
   * Whether the dribble attempt succeeded or failed.
   */
  takeOnResult: "complete" | "incomplete";
  /**
   * Source provider identifier such as opta, statsbomb, or whoscored.
   */
  provider: string;
  /**
   * Raw event identifier from the source provider.
   */
  providerEventId: string;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical lineup or bench player entry for a match-day team sheet.
 */
export interface TeamSheetPlayer {
  /**
   * Stable provider or canonical player identifier.
   */
  playerId: string;
  /**
   * Display-ready player name when known.
   */
  label?: string | null;
  /**
   * Shirt number when the source provides it.
   */
  number?: number | null;
  /**
   * Provider-normalized or canonical position code when known.
   */
  positionCode?: string | null;
  /**
   * Formation slot when the player belongs to a formation snapshot.
   */
  slot?: number | null;
  /**
   * True when this player is the team's captain.
   */
  captain?: boolean;
  /**
   * True when this player is in the starting XI.
   */
  starter?: boolean;
  /**
   * True when the player entered as a substitute.
   */
  substitutedIn?: boolean;
  /**
   * True when the player left the pitch as a substitution.
   */
  substitutedOut?: boolean;
  /**
   * Minute the player entered the pitch, when derivable.
   */
  minuteOn?: number | null;
  /**
   * Minute the player left the pitch, when derivable.
   */
  minuteOff?: number | null;
  /**
   * Provider-supplied player rating when available.
   */
  rating?: number | null;
  /**
   * Campos pitch x-coordinate override when the source provides explicit formation coordinates.
   */
  x?: number | null;
  /**
   * Campos pitch y-coordinate override when the source provides explicit formation coordinates.
   */
  y?: number | null;
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Canonical match-day team sheet for one side of a match.
 */
export interface TeamSheet {
  /**
   * Stable team identifier.
   */
  teamId: string;
  /**
   * Display-ready team label when known.
   */
  teamLabel?: string | null;
  /**
   * Kickoff or current formation label when known.
   */
  formation?: string | null;
  /**
   * Convenience reference for the team's captain.
   */
  captainPlayerId?: string | null;
  /**
   * Starting XI or available starter list.
   */
  starters: TeamSheetPlayer[];
  /**
   * Named substitutes or bench players.
   */
  bench: TeamSheetPlayer[];
  /**
   * Optional broader squad members who are unavailable or outside the named bench.
   */
  unavailable?: TeamSheetPlayer[];
  /**
   * Provider-scoped metadata bag for provenance and advanced debugging. It must stay JSON-serializable, must not duplicate canonical top-level fields, and must not reinterpret raw provider semantics into fake cross-provider meaning.
   */
  sourceMeta?: {
    [k: string]: unknown;
  } | null;
}

/**
 * Team metadata. Only id is required.
 */
export interface Team {
  id: string;
  name?: string | null;
  shortName?: string | null;
  [k: string]: unknown;
}
