import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

import { compile } from "json-schema-to-typescript";

const packageRoot = resolve(dirname(new URL(import.meta.url).pathname), "..");
const schemaDir = join(packageRoot, "schema");
const outputFile = join(packageRoot, "src", "generated.ts");

const schemaFiles = (await readdir(schemaDir))
  .filter((file) => file.endsWith(".schema.json"))
  .sort();

const compiled = [];

for (const fileName of schemaFiles) {
  const schemaPath = join(schemaDir, fileName);
  const schema = JSON.parse(await readFile(schemaPath, "utf8"));
  const title = schema.title ?? fileName.replace(/\.schema\.json$/, "");
  const ts = await compile(schema, title, {
    bannerComment: "",
    cwd: schemaDir,
    declareExternallyReferenced: false,
    style: {
      singleQuote: false,
      semi: true,
    },
  });
  compiled.push(ts.trim());
}

const output = `// This file is generated by packages/schema/scripts/generate-types.mjs.\n// Do not edit it by hand.\n\n${compiled.join("\n\n")}\n`;

await mkdir(dirname(outputFile), { recursive: true });
await writeFile(outputFile, output);
